packages:
  - alamos/ts
  - client/ts
  - configs/**
  - console
  - docs/site
  - docs/videos
  - drift
  - freighter/ts
  - integration/ts
  - pluto
  - x/media
  - x/ts

catalog:
  "@eslint/compat": "^1.2.7"
  "@fontsource/geist-mono": "^5.2.5"
  "@reduxjs/toolkit": "^2.6.1"
  "@tauri-apps/api": "^2.4.1"
  "@testing-library/react": "^16.3.0"
  "@types/node": "^22.13.10"
  "@types/react": "^19.1.0"
  "@types/react-dom": "^19.1.1"
  "@types/uuid": "^10.0.0"
  "@vitejs/plugin-react": "^4.3.4"
  async-mutex: "^0.5.0"
  clsx: "^2.1.1"
  eslint: "^9.24.0"
  madge: "^8.0.0"
  node-fetch: "^2.7.0"
  prettier: "^3.5.3"
  proxy-memoize: "2.0.3"
  react: "^19.1.0"
  react-dom: "^19.1.0"
  react-icons: "^5.5.0"
  react-redux: "^9.2.0"
  typescript: "^5.8.3"
  uuid: "^11.1.0"
  vite: "^6.2.5"
  vitest: "^3.1.1"
  zod: "^3.24.2"
