name: Test - X (C++)

on:
  push:
    branches:
      - main
      - rc
    paths:
      - .bazeliskrc
      - .bazelrc
      - .clang-format
      - .github/workflows/test.x.cpp.yaml
      - MODULE.bazel
      - MODULE.bazel.lock
      - x/cpp/**
      - x/go/**/*.pb.go
  pull_request:
    paths:
      - .bazeliskrc
      - .bazelrc
      - .clang-format
      - .github/workflows/test.x.cpp.yaml
      - MODULE.bazel
      - MODULE.bazel.lock
      - x/cpp/**
      - x/go/**/*.pb.go
  workflow_dispatch:

jobs:
  test:
    name: Test (${{ matrix.os }})
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            lint: true
        exclude:
          - os:
              ${{ (github.ref != 'refs/heads/main' || github.base_ref != 'main') &&
              'macos-latest' }}
          - os:
              ${{ (github.ref != 'refs/heads/main' || github.base_ref != 'main') &&
              'windows-latest' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Check Formatting
        if: matrix.lint
        run: bash scripts/check-clang-format.sh x/cpp

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Test
        run: bazel test --test_output=all //x/cpp/... --nocache_test_results
