name: Test - Alamos

on:
  push:
    branches:
      - main
      - rc
  pull_request:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      py: ${{ steps.filter.outputs.py }}
      ts: ${{ steps.filter.outputs.ts }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            shared: &shared
              - .github/workflows/test.alamos.yaml
            ts:
              - *shared
              - alamos/ts/**
              - configs/eslint/**
              - configs/ts/**
              - configs/vite/**
              - x/ts/**


  ts:
    name: TypeScript (${{ matrix.os }})
    needs: changes
    if: needs.changes.outputs.ts == 'true'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            lint: true
        exclude:
          - os: ${{ github.ref != 'refs/heads/main' && 'macos-latest' }}
          - os: ${{ github.ref != 'refs/heads/main' && 'windows-latest' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:alamos

      - name: Lint
        if: matrix.lint
        run: pnpm lint:alamos

      - name: Test
        run: pnpm test:alamos
